---
- name: "Install & configure apache2 web server on webservers host list"
  hosts: webservers
  remote_user: root
  vars:
    - domain : "naoufelmhadhbi.tn"

  tasks:    
  - name: ensure apache is at the latest version
    apt:
      name: apache2
      state: latest

  - name: stop apache2 service for configuration
    service:
      name: apache2
      state: stopped

  - name: copy index.html file
    template:
      src: index.html.j2
      dest: /var/www/html/index.html

  - name: write the apache config file
    template:
      src: 000-default.conf.j2
      dest: /etc/apache2/sites-enabled/000-default.conf
    notify:
      - restart-apache

  handlers:
    - name: restart-apache
      service:
        name: apache2
        state: restarted
